feat: add E#getGlobalMatrix()
akashic-games/akashic-engine pull request #271
Opened 2021-02-09 05:28 UTC by yu-ogi

## このpull requestが解決する内容
* `E#getGlobalMatrix()` (グローバル座標から見たエンティティの変換行列) を追加します。
* エンティティのレンダリング時に上記を参照するようにします。

## このpull requestが解決しない内容
* `E#getGlobalMatrix()` で代替可能な処理 (`E#localToGlobal()`, `Collision.intersectEntities()` など) の追従
   * こちらは別で対応します。

## 破壊的な変更を含んでいるか?
* なし

2021-02-09 06:56 UTC, xnv requested changes

2021-02-09 06:56 UTC, xnv commented on src/entities/E.ts
> +		} else if (!this._globalMatrix._modified) {
- 親の座標が変化している (modified() が呼ばれている) 状況で、子の `getGlobalMatrix()` を呼ぶと、この条件ではカバーしきれず、正しくない変換行列が返されませんか。
  - ツリーをルートまで辿って、 _modified の立っている祖先がいたらそこから `_updateGlobalMatrix()` して祖先の行列を更新しながら戻ってくる必要があるかと思います。(そのような祖先が一つもなく、自分も _modified でない時、かつその時のみ、そのまま `this._globalMatrix` を返せるはず)
- 一方で、 `render()` でのトラバース中は、明らかに親から global matrix を確定させながら辿っていくので、各エンティティが全てルートまで辿り返すのは無駄な処理になります。(絶対に祖先の _modified は一つも立っていないことが確定しているので)　これとは独立した関数を設けるか、この関数に引数をつけて処理を使い分けるか、方法はともかく `render()` での無駄を省くことも検討したいです。

2021-02-09 06:56 UTC, xnv commented on src/entities/E.ts
> +			matrix.multiplyLeft(entity.getMatrix());
各祖先の行列を都度かけてその度に捨てていくのは計算コストが惜しいように思います。たとえば

- a
  - b
    - c
       - d1
       - d2
       - ...
       - d100

というようなエンティティのツリー構造があった時、 d1 から d100 の `_updateGlobalMatrix()` を求めると、  a, b, c までの変換行列は完全に同一であるにも関わらず 100 回計算されることになります。 

一度計算した global matrix はそのままそのエンティティ (ここで言えば a, b, c) に保存しておきませんか。(別で書いているとおり、その場合でもルートまでのトラバースは避けられませんが、行列をかけながら戻ってくるよりははるかにローコストになると思います)

2021-02-09 06:58 UTC, xnv commented on src/entities/E.ts
> -		if (this.angle || this.scaleX !== 1 || this.scaleY !== 1 || this.anchorX !== 0 || this.anchorY !== 0) {
この条件分岐はここからは消えますが、 `_updateGlobalMatrix()` の中で有用かもしれないです。後でもいいので検証したいです。

2021-02-09 07:14 UTC, dera- approved these changes

2021-02-09 07:21 UTC, yu-ogi commented on src/entities/E.ts
> +		} else if (!this._globalMatrix._modified) {
> 親の座標が変化している (modified() が呼ばれている) 状況で、～

あー、たしかにそうですね。当該のテストを追加してみます。

2021-02-10 04:41 UTC, yu-ogi commented on src/entities/E.ts
> +		} else if (!this._globalMatrix._modified) {
ee50741 一点目の問題については修正しました。

2021-02-10 06:04 UTC, yu-ogi commented on src/entities/E.ts
> -		if (this.angle || this.scaleX !== 1 || this.scaleY !== 1 || this.anchorX !== 0 || this.anchorY !== 0) {
イメージとしては `Matrix` クラスに `translate()` メソッドを新設する感じでしょうか。

2021-02-10 07:45 UTC, yu-ogi commented on src/entities/E.ts
> +			matrix.multiplyLeft(entity.getMatrix());
0cf8da8 「親がエンティティ」かつ「親のエンティティの global matrix を更新する必要がない」場合に親の global matrix を利用するロジックを追加してみました。

2021-02-12 07:01 UTC, xnv commented on src/entities/E.ts
> -		if (this.angle || this.scaleX !== 1 || this.scaleY !== 1 || this.anchorX !== 0 || this.anchorY !== 0) {
はい。第 4, 5 要素に加算するだけの処理が必要になる認識です。

2021-02-15 02:52 UTC, yu-ogi commented on src/entities/E.ts
> +		} else if (!this._globalMatrix._modified) {
bed4c20 `E#getSelfGlobalMatrix()` という形で該当メソッドを切り出してみました。

2021-02-15 03:13 UTC, yu-ogi commented on src/entities/E.ts
> -		if (this.angle || this.scaleX !== 1 || this.scaleY !== 1 || this.anchorX !== 0 || this.anchorY !== 0) {
`Matrix` クラスのリファクタリングが含まれるのでこちらの対応は別にしておきたいです。

2021-02-16 04:40 UTC, xnv commented
うーんと、 `getMatrix()`, `_updateMatrix()` との対称性から現状のコードになっている気がしますが、祖先のトラバースが絡んでかなりやることが違うので、別物として考えた方がいい気がしています。

現状のコードでは、祖先の global matrix が変化する度、すべての子孫は

- `this._needsCalculateGlobalMatrix()`
- `this.parent._needsCalculateGlobalMatrix()`
- `_updateMatrix()` 内の `for` 文

で三回ルートまでツリーを遡ることになっていて、これが本質的に必要な処理という気はあまりしません。また別コメントでも書いていますが、末端方向 (子孫側) の global matrix を求めた時、本質的にはその全祖先の global matrix が求められているはずなのに、その情報を捨てる形になってしまっているのも、ロジックを整理する余地を感じます。

----

もっとストレートに 「global matrix は親から定まる」という性質を再帰でそのまま記述する方が、処理コスト的にもコード的にも単純にならないでしょうか。つまり、global matrix を更新するとは、

1. 親の global matrix を更新する (a)
2. 自分の global matrix を、(親の global matrix) × (自分の local matrix) で更新する (b)

というだけの処理に思えます。

具体的に言うとこんな感じで済まないかと思っています。

- `getGlobalMatrix()`
   - `_updateGlobalMatrix()` して、 `this._globalMatrix` を返す
- `_updateGlobalMatrix(): boolean` 
  1. 親 の `_updateGlobalMatrix()` を呼ぶ (a に対応)
  2. ↑の戻り値を引数にして `this._updateOwnGlobalMatrix()` を呼び、その戻り値を返す (b に対応)
- `_updateOwnGlobalMatrix(hasModParent: boolean): boolean`
  1. 次のどちらでもなければ false を返して抜ける
     - 親の行列に変更がある (`hasModParent`)
     - 自分の global matrix の _modified が立っている
  1. 親の global matrix を自分の global matrix にコピーする (親がなければ reset())
  2. local matrix (`this.getMatrix()`) を自分の global matrix に `multiply()` する
     - (条件を満たせば `this.x`, `this.y` で translate だけできる)
  3. true を返す

これで通れば、 `render()` の時は  `_updateOwnGlobalMatrix()` だけ呼ぶ (祖先の更新を省略できる) ような形で劇的に簡略にできそうな気がしています。

2021-02-16 08:34 UTC, yu-ogi commented on src/entities/E.ts
> +		renderer.setTransform(this._getSelfGlobalMatrix()._matrix);
ここで `setTransform()` をしてしまうと以下の focusingCamera の変換行列を上書きしてしまう問題に気付き、対応を検討中です。

https://github.com/akashic-games/akashic-engine/blob/8df60d17866322108cdd98855cf538ec2a5ad990/src/Game.ts#L999-L1002

2021-02-17 01:35 UTC, yu-ogi commented on src/Object2D.ts
> +			this._matrix._modified = true;
ロジックが複雑な割にはパフォーマンスへの影響はほぼ無いだろうと判断し、常に matrix を保持するように変更しています。
(生成直後に modified フラグをつけるのが不格好ですが)

2021-02-17 02:30 UTC, yu-ogi commented on src/entities/E.ts
> +		renderer.setTransform(this._getSelfGlobalMatrix()._matrix);
d93efe8 setTransform の利用をやめて transform を利用するように修正しました。

2021-02-17 05:14 UTC, xnv requested changes

2021-02-17 05:14 UTC, xnv commented on src/entities/E.ts
> +		renderer.transform(this._globalMatrix._matrix);
うーん、選択肢は

1. 各 global matrix にカメラも含める (Scene の matrix の代わりに `scene.game.focusingCamera` を使う)
2. この箇所で逐一 global matrix をコピーして、そこに camera の matrix を `multiplyLeft()` してから `setTransform()`

ですかねえ。前者の方が効率的な気がしますが、親に繋がってない時にどうするかとかでちょっと処理的・概念的に面倒かもしれません。

2021-02-17 06:41 UTC, yu-ogi commented on src/entities/E.ts
> +		renderer.transform(this._globalMatrix._matrix);
transform を使うならここは修正前に戻さないとだめでしたね。

後者については Camera クラスが matrix を保持していない (matrix を保持しているのは Camera2D クラス) なので必然的に 1. となるでしょうか。
2. の別案としては、この箇所で setTransform -> `Camera#_applyTransformToRenderer()` で Renderer の transform を設定する (`g.Game#render()` から処理を移す) というのもアリかもしれません。

2021-02-17 07:44 UTC, yu-ogi commented on src/entities/E.ts
> +			this._globalMatrix = this.parent._globalMatrix.clone();
e27a475 既存処理には影響ないだろうと考えて `Matrix#copy()` を追加しました。

2021-02-17 07:45 UTC, yu-ogi commented on src/entities/E.ts
> +		renderer.transform(this._globalMatrix._matrix);
この部分は一旦 revert しました。global matrix と focusingCamera の関係についてはもう少し検討してみます。

2021-02-17 07:46 UTC, yu-ogi commented on src/entities/E.ts
> +			hasModified = this._globalMatrix._modified;
36f693d こちら修正しました。

2021-02-17 10:50 UTC, xnv commented on src/entities/E.ts
> +		renderer.transform(this._globalMatrix._matrix);
(備忘雑感走り書き)

- ワールド座標系にあたる global matrix と、カメラの座標系に対応する camera matrix がある
  - 描画上必要なのは  camera matrix
  - エンティティに持たせたいのはどちらかというと global matrix な気がする (両方あるのが理想？)
- E が global matrix を持つと、
  - render で「camera の matrix をコピー」→「global matrix を掛ける」処理が必要
  - これは現 master の「親の camera matrix をコピー」→「local matrix を掛ける」処理と比べて計算コスト面で優位性がない (global matrix のキャッシュ分メモリ消費を増やしたにも関わらず) (なんなら global matrix を求めるために親の global matrix をコピーする分だけ (render に限れば) 分が悪いまである)
- E が camera matrix を持つと、
  - render は「camera matrix を `setTransform()`」一発でよい
  - カメラが動いた時、すべての matrix を上から計算しなおすことになる (計算コスト面での優位性がない)
  - カメラが動かなければ、 祖先と自分が動いていないエンティティの camera matrix は全て再利用できる可能性があり、これは計算コストの軽減に寄与する
  - 問題は、「カメラを使うコンテンツはほとんど常にカメラを動かすのではないか」という点

2021-02-24 23:58 UTC, closed without merging