Fix renovate eslint error
akashic-games/akashic-engine pull request #312
Opened 2021-09-13 06:28 UTC by ShinobuTakahashi

## このpull requestが解決する内容

- `@typescript-eslint/eslint-plugin` のバージョンが低かったためエラーとなったので、`@akashic/eslint-config` のバージョンに合わせて修正。
- テストで no-unused の lint エラーとなっていた箇所を対応

**#298 へマージします。**

## 破壊的な変更を含んでいるか?

- なし

2021-09-13 07:04 UTC, xnv requested changes

2021-09-13 07:04 UTC, xnv commented on src/__tests__/helpers/mock.ts
>  	_pushPostTickTask<T>(fun: () => void, owner: any): void {
これ引っかかるのたぶん `T` ですよね？　`T` は恐らく https://github.com/akashic-games/akashic-engine/commit/1b375e53a9d1c420d76dd52b2891eb658a07a964 の時の私のミスで、消し漏れではないかと思います。使ってないので `<T>` ごと消せると思いますし、そうすればこの disable はなくせそうです。

2021-09-13 07:15 UTC, ShinobuTakahashi commented on src/__tests__/helpers/mock.ts
>  	_pushPostTickTask<T>(fun: () => void, owner: any): void {
ありがとうございます。`<T>` 削除しました。

2021-09-14 03:07 UTC, xnv approved these changes

2021-09-14 03:35 UTC, merged