feat: pdi-types@1.4.0-beta.0 に追従
akashic-games/akashic-engine pull request #395
Opened 2022-07-28 07:29 UTC by yu-ogi

## このpull requestが解決する内容
* `pdi-types@1.4.0-beta.0` に追従します。

2022-07-28 07:30 UTC, yu-ogi commented on src/DynamicGeneratedAssetConfiguration.ts
> +export type DynamicGeneratedAssetConfiguration =
`DynamicGeneratedAsset` という語を導入しています。

2022-07-28 07:32 UTC, yu-ogi commented on src/AssetManager.ts
> +				return resourceFactory.createVectorImageAssetFromString(conf.id, conf.data);
akashic-engine が pdi にユニークな path を渡す方が良いかもしれません。

2022-08-01 05:25 UTC, dera- approved these changes
コメントしましたが、approveします

2022-08-01 05:25 UTC, dera- commented on src/AssetManager.ts
> +type AssetIdOrConf = string | DynamicAssetConfiguration | DynamicGeneratedAssetConfiguration;
このクラス以外でもよく使われるような型に見えるので、exportを付けるもしくは別ファイルで定義するとかしてもいいのではと思えました

2022-08-01 06:53 UTC, xnv approved these changes

2022-08-01 06:53 UTC, xnv commented on src/AssetManager.ts
> +				}
`Dynamic〜` の方だけ呼び出し元で気にしてるのも対称性ないですし、口は `_createAssetFor()` にまとめて、 `_createDynamicGeneratedAssetFor()` はそこから呼ばれるもののはどうでしょうか。

2022-08-01 06:53 UTC, xnv commented on src/AssetManager.ts
> +			assetId = assetIdOrConf.id;
ここも。将来的にもし audio の動的生成をサポートするならそこでも normalize はすることになるでしょうし、 `_normalize〜` が `DynamicGenerated〜` もサポートしてしまうことにして、呼び出し元で区別しない方がシンプルに思えます。

2022-08-01 06:53 UTC, xnv commented on src/AssetManager.ts
>  		}
これ if 文が網羅的でないのが意図的かどうか読み取りづらそうです。ここに入らない＝DynamicGenerated〜 でそれは非サポートである旨、コメントしておきませんか。

2022-08-01 06:53 UTC, xnv commented on src/DynamicGeneratedAssetConfiguration.ts
> +export type DynamicGeneratedAssetConfiguration =
"DynamicAsset" を他の用途に使ったのが悔やまれますね。別で議論したいです。少なくとも英語的には dynamically generated だと思いますし……。

ジャストアイディア:

- `MemoryAsset` - メモリを抽象したものっぽいか？
- `OnMemoryAsset` - [このあたり](https://game.criware.jp/manual/unity_plugin/latest/contents/addon4u_assetsupport_assets_import.html) の語法を踏まえて
- `AssetGeneration` - いっそのこと「アセットの設定/asset configuration」ではなく「アセット生成の設定/configuration of asset geneartion」とみなす

2022-08-01 06:53 UTC, xnv requested changes
すいません間違えて approve しちゃったの撤回です。

2022-08-02 02:45 UTC, yu-ogi commented on src/AssetManager.ts
> +			assetId = assetIdOrConf.id;
この箇所 (`_normalizeAssetBaseDeclaration()` の引数の `conf`) だけ型定義が `T extends AssetConfigurationCore` で他 (`string | DynamicAssetConfiguration`) と違うので呼び出し先で区別するのが型定義上簡単ではなさそうなので、一旦コメントのみの対応とさせてください。

2022-08-02 02:54 UTC, yu-ogi commented on src/AssetManager.ts
> +type AssetIdOrConf = string | DynamicAssetConfiguration | DynamicGeneratedAssetConfiguration;
影響範囲が大きそうなので一旦見送らせてください。

2022-08-02 02:55 UTC, yu-ogi commented on src/DynamicGeneratedAssetConfiguration.ts
> +	type: "image";
紛らわしかったため vector-image 以外の設定は削除してしまいました。

2022-08-02 03:35 UTC, yu-ogi commented on src/DynamicGeneratedAssetConfiguration.ts
> +export type DynamicGeneratedAssetConfiguration =
`AssetGeneration` という後に変更しようと思います。

2022-08-02 07:49 UTC, yu-ogi commented
レビューコメントについて一通り対応しました。

2022-08-03 02:59 UTC, xnv commented on src/AssetGeneration.ts
> +export interface AssetGenerationBase extends AssetConfigurationCommonBase {
……すいません、書き方が悪かった気がしますが `AssetGenerationConfiguration` というつもりで話していました (`DynamicGeneratedAsset` の部分をどうするか、という意味で `AssetGeneration` と書いていました)。

2022-08-03 02:59 UTC, xnv commented on src/__tests__/helpers/mock.ts
> +export class AssetGenerationVectorImageAsset extends pci.VectorImageAsset {
テスト用クラスなので名前はなんでもいい気もしますが、名詞+名詞になっちゃうので、 `GeneratedVectorImageAsset` とするのはどうでしょうか。

全体的に `AssetGenerationConfiguration` から生成されるものは `GeneratedAsset` とでも呼ぶのが座りがいい気がしています。

2022-08-03 02:59 UTC, xnv commented on src/AssetManager.ts
> +	_createFromAssetGenerationFor(conf: AssetGeneration): OneOfAsset {
他に倣うとこれは `_createGeneratedAssetFor()` とかにするのがまとまりそうです。

2022-08-03 04:12 UTC, yu-ogi commented on src/AssetGeneration.ts
> +export interface AssetGenerationBase extends AssetConfigurationCommonBase {
修正しました。

2022-08-03 04:12 UTC, yu-ogi commented on src/__tests__/helpers/mock.ts
> +export class AssetGenerationVectorImageAsset extends pci.VectorImageAsset {
修正しました。

2022-08-03 04:13 UTC, yu-ogi commented on src/AssetManager.ts
> +	_createFromAssetGenerationFor(conf: AssetGeneration): OneOfAsset {
修正しました。

2022-08-03 05:54 UTC, xnv approved these changes
コメント加えていますが approved.

2022-08-03 05:54 UTC, xnv commented on src/index.common.ts
> +export * from "./AssetGenerationConfiguration";
何も実害ありませんが辞書順なら AssetHolder より AssetGeneration〜 の方が先かと思います。

2022-08-03 07:16 UTC, yu-ogi commented on src/index.common.ts
> +export * from "./AssetGenerationConfiguration";
あ、別のコミットで入れ替わってしまいましたね...
修正しました。

2022-08-03 08:00 UTC, merged